name: mock_supabase_http_client
description: A mock supabase http client for testing Supabase APIs
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: '>=0.13.0 <2.0.0'
  supabase: ^2.0.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
