name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test SDK ${{ matrix.sdk }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        sdk: [stable, beta, dev]

    defaults:
      run:
        working-directory: packages/postgrest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checks-out repo
        uses: actions/checkout@v4

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}

      - name: Install dependencies
        run: dart pub get

      - name: dartfmt
        if: ${{ matrix.sdk == 'stable'}}
        run: dart format lib test -l 80 --set-exit-if-changed

      - name: analyzer
        run: dart analyze --fatal-warnings --fatal-infos .

      - name: Run tests
        run: dart test
